apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: docker.io/90041/myimage:v1
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: icr
